# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e2eb8a55a773550180dcd2e27e241670"
name = "oZone Sender"
handle = "ozone-sms-app"
application_url = "https://dishes-departmental-unions-bt.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ozone-test-shop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://dishes-departmental-unions-bt.trycloudflare.com/auth/callback",
  "https://dishes-departmental-unions-bt.trycloudflare.com/auth/shopify/callback",
  "https://dishes-departmental-unions-bt.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled", "orders/create" ]
  uri = "https://synthetic-draft-water-california.trycloudflare.com/webhooks"

[pos]
embedded = true
