# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b1bac9784e4eac92831998284468c1b"
name = "ff"
handle = "ff-14"
application_url = "https://glad-tan-bi-organisation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "newstore-f1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://glad-tan-bi-organisation.trycloudflare.com/auth/callback",
  "https://glad-tan-bi-organisation.trycloudflare.com/auth/shopify/callback",
  "https://glad-tan-bi-organisation.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
