# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7881f8b703dc249967cbc60d44aa5405"
name = "oZoneSender"
handle = "ozonesender"
application_url = "https://missouri-bedroom-metabolism-cincinnati.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "newstore-f1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://missouri-bedroom-metabolism-cincinnati.trycloudflare.com/auth/callback",
  "https://missouri-bedroom-metabolism-cincinnati.trycloudflare.com/auth/shopify/callback",
  "https://missouri-bedroom-metabolism-cincinnati.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
